[tool.pylint.main]
disable = [
    "too-few-public-methods",  # Django REST needs classes that just have attributes.
    "no-member"                # Django creates methods for models.
]
ignore-paths = "src/affiliations/migrations"
