# Generated by Django 5.2.6 on 2026-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0049_affiliation_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicaldomainworkinggroup",
            name="uuid",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="GPM UUID"
            ),
        ),
    ]
