name: continuous integration
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Format
        run: invoke fmt
      - name: lint
        run: invoke lint
      - name: check types
        run: invoke types
      - name: run tests
        run: invoke test
